---
# =============================================================================
# LEAF NODE DEFINITIONS
# =============================================================================
type: l3leaf

l3leaf:
  defaults:
    platform: cEOSLab
    loopback_ipv4_pool: 192.168.255.0/27
    loopback_ipv4_offset: 2
    vtep_loopback_ipv4_pool: 192.168.254.0/27
    uplink_switches: [spine1]
    uplink_interfaces: [Ethernet1]
    uplink_ipv4_pool: 192.168.103.0/24
    bgp_defaults:
      - no bgp default ipv4-unicast
    spanning_tree_mode: mstp
    spanning_tree_priority: 4096

  nodes:
    - name: leaf1
      id: 1
      bgp_as: "65101"
      uplink_switch_interfaces: [Ethernet1]

    - name: leaf2
      id: 2
      bgp_as: "65102"
      uplink_switch_interfaces: [Ethernet2]
