---
# =============================================================================
# SPINE NODE DEFINITIONS
# =============================================================================
type: spine

spine:
  defaults:
    platform: cEOSLab
    bgp_as: "65001"
    loopback_ipv4_pool: 192.168.255.0/27
    bgp_defaults:
      - no bgp default ipv4-unicast

  nodes:
    - name: spine1
      id: 1
